### PR TITLE
Openshiftv3

### PR DESCRIPTION
**Pull request by jasinner**
These changes are needed for deployment to OCP 3 version of Openshift Online.

### CODE REVIEW

**Comment by ashcrow** [comment]
@jasinner thanks for providing this. I'll take a look at it and update it for passing CI. Were you able to get this working or is this foundation work?

**Comment by ashcrow** [comment]
@jasinner why did you end up removing the ``setup.py`` and ``requirements.txt`` files in af4222c525b8c67fb3bae25c6d36f9e7dd295eda?

**Comment by jasinner** [comment]
Hrm, not sure how to get these nosetests working again. Seems to be failing with an Error. Any idea @ashcrow ?

**Comment by ashcrow** [comment]
@jasinner the error looks to be that the cache key doesn't exist. Oddly enough it seems like it's attempting to request based off an object instance (which doesn't make a lot of sense IMHO). My quick guess is that ``Flask-Cache`` may have been upgraded yet we are requiring older versions of some code. https://github.com/victims/victims-web/blob/master/requirements.txt#L6

**Comment by jasinner** [comment]
Thanks @ashcrow, I'll try adjusting the Flask-Cache version. 
I did get the Openshift starter deployment working today, [check it out.](http://web-victims-web.1d35.starter-us-east-1.openshiftapps.com/).  It doesn't have any data yet, as I found migrating the whole database problematic before, I think we should just reseed a minimal set of data, including users at first.

**Comment by ashcrow** [comment]
@jasinner fantastic! Great work!

**Comment by abn** [comment]
@jasinner first off - great work, was looking forward to seeing this on v3. I do not think the code changes here are really required for a v3 deployment; things like moving to a relative package referencing is not something I'd recommend in this scenario. Additionally, you might be better off with overriding the s2i scripts than using the app's developer defaults at run time. Would be great if we can discuss some of the higher level objectives sometime soon (but that is par of another piece of work).

I'll try and carve out some time next week for this work.

**Comment by abn** [comment]
I have made a few changes in PR #150 this will improve package handling etc. I'd recommend closing this one and the previous PR in favour of that one. Granted that does not "complete" the OpenShift migration but its a step in the right direction.

**Pull request closed without merging**
